### ISSUE TITLE
Support quotes around keys

### ISSUE THREAD

**Issue by SamVerschueren** [hjson/hjson-js#16]
Hi, I really like this library as it allows me to add comments to my JSON files. That is the only feature I want (for now) as I like to use this as config parser for [alfy](https://github.com/sindresorhus/alfy).

What I noticed however, is that it does two things that keeps me from using this library.

#### No trailing commas
The output of the `stringify` call returns key-value pairs without commas. So this is what I get
```json
{
    foo: "bar"
    unicorn: "rainbow"
}
```

This is probably intended. I think it would be nice if there was an option to at least allow trailing commas to be added.

#### Quotes around keys
By default, it doesn't quote anything, not even string values. So I used the `quotes` option and set it to `always`. This adds quotes around string values, but not around keys. It might make sense if there was an extra option like `min`, `values`, `always` or something. Where `always` also wraps the keys.

// @sindresorhus

**Comment by SamVerschueren** [comment]
I can also do a PR if you want.

**Comment by laktak** [comment]
> I can also do a PR if you want.

That would be great! 

Please make your changes non breaking though. How about `min`, `keys`, `strings` and `all` for the `quotes` option? `always` should be kept but can be deprecated and would give the same output as `strings`.

Since #15 adds an option for multiline strings with tabs (which I guess you'd want to treat as regular strings) this could probably be combined into a single `multiline` option.

Btw, I don't want to be nitpicking but "trailing commas" are the ones that break JSON, you probably just want the commas between elements ;)

**Comment by SamVerschueren** [comment]
> How about min, keys, strings and all for the quotes option? always should be kept but can be deprecated and would give the same output as strings.

Sounds good!

> you probably just want the commas between elements ;)

Yes sorry, I didn't mean trailing comma's at the end of objects or arrays. Just in between :).

> Since #15 adds an option for multiline strings with tabs (which I guess you'd want to treat as regular strings) this could probably be combined into a single multiline option.

Could you elaborate what you're referring to?

----------------

I will make a separate issue to track the commas between elements. This way I can make separate PRs and refer to the correct issue.

**Comment by laktak** [comment]
> Could you elaborate what you're referring to?

PR #15 added an option for multiline strings (see https://github.com/hjson/hjson-js/blob/master/lib/hjson.js#L51) and the same option could accept an "off" switch.
